name: Update Electricity Prices

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  update-prices:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install nordpool

      - name: Fetch latest electricity prices
        run: python data/live_energy_data.py

      - name: Commit updated price file
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/latest_prices.csv
          git commit -m "update electricity prices" || echo "no changes"
          git push